/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import captcha.CaptchaPanel;

/**
 *
 * @author Usuario1
 */
public class Capt extends javax.swing.JDialog {

    private boolean captchaValidado = false;

    /**
     * Creates new form Capt
     */
    public Capt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Captcha");
        setLocationRelativeTo(null);
    }

    public boolean isCaptchaValido() {
        return this.captchaValidado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cpchaPanel = new captcha.CaptchaPanel();
        lblCaptcha = new javax.swing.JLabel();
        txtCaptcha = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JToggleButton();
        lblErrorCaptcha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adobe Express - file (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 60));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout cpchaPanelLayout = new javax.swing.GroupLayout(cpchaPanel);
        cpchaPanel.setLayout(cpchaPanelLayout);
        cpchaPanelLayout.setHorizontalGroup(
            cpchaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        cpchaPanelLayout.setVerticalGroup(
            cpchaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(cpchaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        lblCaptcha.setForeground(new java.awt.Color(153, 153, 153));
        lblCaptcha.setText("Ingrese el texto captcha");
        jPanel2.add(lblCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 130, -1));

        txtCaptcha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCaptchaMouseClicked(evt);
            }
        });
        txtCaptcha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCaptchaKeyPressed(evt);
            }
        });
        jPanel2.add(txtCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 150, 40));

        btnVerificar.setBackground(new java.awt.Color(51, 102, 255));
        btnVerificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerificar.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        lblErrorCaptcha.setFont(new java.awt.Font("Pristina", 1, 14)); // NOI18N
        jPanel2.add(lblErrorCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 160));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura de pantalla 2025-07-21 185900.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 380, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCaptchaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCaptchaMouseClicked
        // TODO add your handling code here:
        lblCaptcha.setVisible(false);
    }//GEN-LAST:event_txtCaptchaMouseClicked

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        String Captcha = txtCaptcha.getText();
        String CodigoCorrecto = cpchaPanel.getCodigo().trim();

        if (!Captcha.equalsIgnoreCase(CodigoCorrecto)) {
            lblErrorCaptcha.setText("Captcha incorrecto");
            lblErrorCaptcha.setForeground(java.awt.Color.RED);
            cpchaPanel.generarCaptcha();
            txtCaptcha.setText("");
            lblCaptcha.setVisible(true);
            this.captchaValidado = false;  // <- Añade esto
        } else {
            this.captchaValidado = true;   // <- Cambia esto (elimina las líneas de IngresoalSistema)
            dispose();
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void txtCaptchaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCaptchaKeyPressed
        // TODO add your handling code here:
        lblCaptcha.setVisible(false);
    }//GEN-LAST:event_txtCaptchaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Capt dialog = new Capt(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnVerificar;
    private captcha.CaptchaPanel cpchaPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCaptcha;
    private javax.swing.JLabel lblErrorCaptcha;
    private javax.swing.JTextField txtCaptcha;
    // End of variables declaration//GEN-END:variables
}
