/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.sql.*;
import Conexion.ConexionBD;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import barradeprogreso.BarradeProgreso;
import javax.swing.SwingUtilities;
import captcha.CaptchaPanel;
import javax.swing.JProgressBar;


/**
 *
 * @author Usuario1
 */
public class Loggin extends javax.swing.JFrame {

    public static Registro reg;
    Conexion.ConexionBD con = new ConexionBD();
    Connection cn;

    /**
     * Creates new form Loggin
     */
    public Loggin() throws SQLException {
        this.cn = ConexionBD.getConexion();
        initComponents();
        setTitle("Login");
        this.lblOjoCerrado.setVisible(false);
        brraProgreso.setVisible(false);
    }

    private void mostrarError(String mensaje) {
        lblErrorIngreso.setText(mensaje);
        lblErrorIngreso.setForeground(Color.RED);
    }

    private void mostrarExito(String mensaje) {
        lblErrorIngreso.setText(mensaje);
        lblErrorIngreso.setForeground(new Color(0, 100, 0)); // Verde oscuro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnIngresar = new javax.swing.JButton();
        lblOjoAbierto = new javax.swing.JLabel();
        lblOjoCerrado = new javax.swing.JLabel();
        brraProgreso = new barradeprogreso.BarradeProgreso();
        lblContra = new javax.swing.JLabel();
        txtContra = new javax.swing.JPasswordField();
        lblErrorIngreso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adobe Express - file.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, 190));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura de pantalla 2025-07-21 185900.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 430, 400));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura de pantalla 2025-07-21 185900.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 430, 300));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Headline (2).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Correo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        lblCorreo.setForeground(new java.awt.Color(153, 153, 153));
        lblCorreo.setText("Ingrese su correo");
        jPanel2.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 270, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jCheckBox1.setText("Recuerdame");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 20));

        btnIngresar.setBackground(new java.awt.Color(255, 51, 51));
        btnIngresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 270, 30));

        lblOjoAbierto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-eye-32.png"))); // NOI18N
        lblOjoAbierto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOjoAbiertoMouseClicked(evt);
            }
        });
        jPanel2.add(lblOjoAbierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        lblOjoCerrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-ojo-cerrado-32.png"))); // NOI18N
        lblOjoCerrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOjoCerradoMouseClicked(evt);
            }
        });
        jPanel2.add(lblOjoCerrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        brraProgreso.setColorBarra(new java.awt.Color(0, 153, 0));
        brraProgreso.setTextoPersonalizado("Cargando.");
        jPanel2.add(brraProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 380, 20));
        brraProgreso.getAccessibleContext().setAccessibleName("");

        lblContra.setForeground(new java.awt.Color(153, 153, 153));
        lblContra.setText("Ingrese su contraseña");
        jPanel2.add(lblContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        txtContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraMouseClicked(evt);
            }
        });
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraKeyPressed(evt);
            }
        });
        jPanel2.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 270, 40));

        lblErrorIngreso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel2.add(lblErrorIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 420, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 480, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOjoAbiertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOjoAbiertoMouseClicked
        // TODO add your handling code here:
        lblOjoAbierto.setVisible(false);
        lblOjoCerrado.setVisible(true);
        txtContra.setEchoChar((char) 0);
    }//GEN-LAST:event_lblOjoAbiertoMouseClicked

    private void lblOjoCerradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOjoCerradoMouseClicked
        // TODO add your handling code here:
        lblOjoAbierto.setVisible(true);
        lblOjoCerrado.setVisible(false);
        txtContra.setEchoChar('●');
    }//GEN-LAST:event_lblOjoCerradoMouseClicked

    private void txtContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraMouseClicked
        // TODO add your handling code here:
        lblContra.setVisible(false);
    }//GEN-LAST:event_txtContraMouseClicked

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
        lblCorreo.setVisible(false);
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String correo = txtCorreo.getText().trim();
        String contra = new String(txtContra.getPassword()).trim();

        if (correo.isEmpty() || contra.isEmpty()) {
            mostrarError("Debe completar los datos obligatorios. Verifique.");
            return;
        }

        // Validar captcha primero
        Capt captDialog = new Capt(null, true);
        captDialog.setVisible(true);

        if (!captDialog.isCaptchaValido()) {
            lblErrorIngreso.setText("Captcha no validado. Acceso denegado.");
            lblErrorIngreso.setForeground(Color.RED);
            return;
        }

        // Configurar barra de progreso
        brraProgreso.setVisible(true);
        brraProgreso.reiniciar(); // Asegurarse que empiece desde 0
        brraProgreso.iniciar();   // Iniciar animación automática

        new Thread(() -> {
            try {
                // Esperar a que la barra llegue al 100%
                while (brraProgreso.getProgreso() < 100) {
                    Thread.sleep(100); // Verificar cada 100ms
                }

                // Autenticación con BD
                try (PreparedStatement ps = cn.prepareStatement(
                        "SELECT id_tipo_empleado FROM empleados WHERE correo = ? AND contraseña = ?")) {

                    ps.setString(1, correo);
                    ps.setString(2, contra);

                    try (ResultSet rs = ps.executeQuery()) {
                        SwingUtilities.invokeLater(() -> {
                            try {
                                if (rs.next()) {
                                    String tipoEmpleado = rs.getString("id_tipo_empleado");
                                    dispose(); // Cerrar login

                                    switch (tipoEmpleado) {
                                        case "1":
                                            new IngresoalSistema().setVisible(true);
                                            break;
                                        case "2":
                                            new Veterinarios().setVisible(true);
                                            break;
                                        case "4":
                                            new Recepcion().setVisible(true);
                                            break;
                                        default:
                                            mostrarError("Rol no reconocido");
                                    }
                                } else {
                                    mostrarError("Credenciales incorrectas");
                                }
                            } catch (SQLException ex) {
                                mostrarError("Error al leer datos: " + ex.getMessage());
                            }
                        });
                    }
                }
            } catch (InterruptedException | SQLException e) {
                SwingUtilities.invokeLater(() -> {
                    mostrarError("Error: " + e.getMessage());
                    brraProgreso.detener();
                });
            } finally {
                brraProgreso.setVisible(false);
            }
        }).start();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        // TODO add your handling code here:
        lblCorreo.setVisible(false);
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyPressed
        // TODO add your handling code here:
        lblContra.setVisible(false);
    }//GEN-LAST:event_txtContraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Loggin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Loggin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private barradeprogreso.BarradeProgreso brraProgreso;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblErrorIngreso;
    private javax.swing.JLabel lblOjoAbierto;
    private javax.swing.JLabel lblOjoCerrado;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
