/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import java.sql.*;
import Conexion.ConexionBD;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import correo.EnviarCorreo;
import correo.GenerarPDF;

/**
 *
 * @author Usuario1
 */
public class Registro extends javax.swing.JDialog {

    Conexion.ConexionBD con = new ConexionBD();
    Connection cn;

    /**
     * Creates new form Registro
     */
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            this.cn = con.getConexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos",
                    "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setTitle("Registro");
        this.lblOjoCerrado.setVisible(false);
    }

    private void mostrarError(String mensaje) {
        lblErrorIngreso.setText(mensaje);
        lblErrorIngreso.setForeground(Color.RED);
    }

    private void mostrarExito(String mensaje) {
        lblErrorIngreso.setText(mensaje);
        lblErrorIngreso.setForeground(new Color(0, 100, 0)); // Verde oscuro
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellidos.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtEspecialidad.setText("");
        txtContraseña.setText("");
        cboTipoEmpleado.setSelectedIndex(0);

        // Restaurar placeholders
        lblNombre.setVisible(true);
        lblApellidos.setVisible(true);
        lblTelefono.setVisible(true);
        lblCorreo.setVisible(true);
        lblDireccion.setVisible(true);
        lblEspecialidad.setVisible(true);
        lblContraseña.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboTipoEmpleado = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        lblErrorIngreso = new javax.swing.JLabel();
        lblOjoAbierto = new javax.swing.JLabel();
        lblOjoCerrado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, 20));

        lblNombre.setForeground(new java.awt.Color(153, 153, 153));
        lblNombre.setText("Ingrese nombre");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Apellidos");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 70, 20));

        lblApellidos.setForeground(new java.awt.Color(153, 153, 153));
        lblApellidos.setText("Ingrese apellidos");
        jPanel2.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 110, -1));

        txtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidosMouseClicked(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidosKeyPressed(evt);
            }
        });
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 300, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Teléfono");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 20));

        lblTelefono.setForeground(new java.awt.Color(153, 153, 153));
        lblTelefono.setText("Ingrese número teléfonico");
        jPanel2.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 150, -1));

        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseClicked(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Correo");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 70, 20));

        lblCorreo.setForeground(new java.awt.Color(153, 153, 153));
        lblCorreo.setText("Ingrese correo electrónico");
        jPanel2.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 150, -1));

        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 300, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Dirección");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, 20));

        lblDireccion.setForeground(new java.awt.Color(153, 153, 153));
        lblDireccion.setText("Ingrese dirección");
        jPanel2.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, -1));

        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDireccionMouseClicked(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
        });
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 390, 40));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Tipo empleado");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 90, 20));

        cboTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Administrador", "Veterinario", "Asistente", "Recepcionista" }));
        jPanel2.add(cboTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 180, 40));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Especialidad");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, 20));

        lblEspecialidad.setForeground(new java.awt.Color(153, 153, 153));
        lblEspecialidad.setText("Ingrese especialidad (Veterinarios)");
        jPanel2.add(lblEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        txtEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEspecialidadMouseClicked(evt);
            }
        });
        txtEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEspecialidadKeyPressed(evt);
            }
        });
        jPanel2.add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 260, 40));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Contraseña");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 70, 20));

        lblContraseña.setForeground(new java.awt.Color(153, 153, 153));
        lblContraseña.setText("Ingrese contraseña");
        jPanel2.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 150, -1));

        btnRegistrar.setBackground(new java.awt.Color(51, 102, 255));
        btnRegistrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 180, 40));

        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyPressed(evt);
            }
        });
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 300, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Headline (5).png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        lblErrorIngreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(lblErrorIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 600, 30));

        lblOjoAbierto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-eye-32.png"))); // NOI18N
        lblOjoAbierto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOjoAbiertoMouseClicked(evt);
            }
        });
        jPanel2.add(lblOjoAbierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 438, 30, -1));

        lblOjoCerrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-ojo-cerrado-32.png"))); // NOI18N
        lblOjoCerrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOjoCerradoMouseClicked(evt);
            }
        });
        jPanel2.add(lblOjoCerrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 720, 600));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura de pantalla 2025-07-21 185900.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura de pantalla 2025-07-21 185900.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -20, 430, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String telefonoStr = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String direccion = txtDireccion.getText().trim();
        String tipoempleado = cboTipoEmpleado.getSelectedItem().toString().trim();
        String especialidad = txtEspecialidad.getText().trim();
        String contraseña = new String(txtContraseña.getPassword()).trim();

        // Validaciones básicas
        if (nombre.isEmpty() || apellidos.isEmpty() || telefonoStr.isEmpty()
                || correo.isEmpty() || direccion.isEmpty() || contraseña.isEmpty()) {
            mostrarError("Debe completar los datos obligatorios. Verifique.");
            return;
        }

        if (tipoempleado.equals("Seleccionar")) {
            mostrarError("Seleccione un tipo de empleado.");
            return;
        }

        // Validar teléfono
        if (!telefonoStr.matches("\\d{8,15}")) {
            mostrarError("El teléfono debe contener solo números (8-15 dígitos).");
            return;
        }

        // Validar correo electrónico
        if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            mostrarError("Ingrese un correo electrónico válido.");
            return;
        }

        // Validación especial para veterinarios
        if (tipoempleado.equalsIgnoreCase("Veterinario") && especialidad.isEmpty()) {
            mostrarError("Los veterinarios deben especificar una especialidad.");
            return;
        }

        try {
            // Convertir el tipo de empleado a ID numérico
            int idTipo = switch (tipoempleado) {
                case "Administrador" ->
                    1;
                case "Veterinario" ->
                    2;
                case "Asistente" ->
                    3;
                case "Recepcionista" ->
                    4;
                default -> {
                    mostrarError("Tipo de empleado no válido.");
                    yield 0;
                }
            };

            if (idTipo == 0) {
                return; // No continuar si el tipo no es válido
            }
            // Preparar la consulta SQL
            String consulta = "INSERT INTO empleados (nombre, apellidos, telefono, direccion, correo, contraseña, especialidad, id_tipo_empleado) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement ps = cn.prepareStatement(consulta);
            ps.setString(1, nombre);
            ps.setString(2, apellidos);
            ps.setString(3, telefonoStr);
            ps.setString(4, direccion);
            ps.setString(5, correo);
            ps.setString(6, contraseña);
            ps.setString(7, especialidad.isEmpty() ? null : especialidad); // Manejo de nulos para no veterinarios
            ps.setInt(8, idTipo);

            // Ejecutar la inserción
            int filasAfectadas = ps.executeUpdate();

            if (filasAfectadas > 0) {
                mostrarExito("Empleado registrado exitosamente!");
                limpiarCampos();
                dispose();
            } else {
                mostrarError("No se pudo registrar el empleado.");
            }

        } catch (SQLException e) {
            mostrarError("Error de base de datos: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            mostrarError("Error inesperado: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
        lblNombre.setVisible(false);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        lblNombre.setVisible(false);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyPressed
        // TODO add your handling code here:
        lblApellidos.setVisible(false);
    }//GEN-LAST:event_txtApellidosKeyPressed

    private void txtApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosMouseClicked
        // TODO add your handling code here:
        lblApellidos.setVisible(false);
    }//GEN-LAST:event_txtApellidosMouseClicked

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        // TODO add your handling code here:
        lblTelefono.setVisible(false);
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseClicked
        // TODO add your handling code here:
        lblTelefono.setVisible(false);
    }//GEN-LAST:event_txtTelefonoMouseClicked

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        // TODO add your handling code here:
        lblCorreo.setVisible(false);
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
        lblCorreo.setVisible(false);
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
        // TODO add your handling code here:
        lblDireccion.setVisible(false);
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void txtDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMouseClicked
        // TODO add your handling code here:
        lblDireccion.setVisible(false);
    }//GEN-LAST:event_txtDireccionMouseClicked

    private void txtEspecialidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecialidadKeyPressed
        // TODO add your handling code here:
        lblEspecialidad.setVisible(false);
    }//GEN-LAST:event_txtEspecialidadKeyPressed

    private void txtEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEspecialidadMouseClicked
        // TODO add your handling code here:
        lblEspecialidad.setVisible(false);
    }//GEN-LAST:event_txtEspecialidadMouseClicked

    private void txtContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyPressed
        // TODO add your handling code here:
        lblContraseña.setVisible(false);
    }//GEN-LAST:event_txtContraseñaKeyPressed

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        // TODO add your handling code here:
        lblContraseña.setVisible(false);
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void lblOjoAbiertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOjoAbiertoMouseClicked
        // TODO add your handling code here:
        lblOjoAbierto.setVisible(false);
        lblOjoCerrado.setVisible(true);
        txtContraseña.setEchoChar((char) 0);
    }//GEN-LAST:event_lblOjoAbiertoMouseClicked

    private void lblOjoCerradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOjoCerradoMouseClicked
        // TODO add your handling code here:
        lblOjoAbierto.setVisible(true);
        lblOjoCerrado.setVisible(false);
        txtContraseña.setEchoChar('●');
    }//GEN-LAST:event_lblOjoCerradoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro dialog = null;
                dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboTipoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblErrorIngreso;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOjoAbierto;
    private javax.swing.JLabel lblOjoCerrado;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
